name: mink_global_player
description: A global audio player manager
version: 0.0.8
repository: https://github.com/krikristoophe/mink_global_player

publish_to: none


environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.0
  build_runner: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms: 
      web:
        default_package: mink_global_player_web
